export type RelationshipGender = "male" | "female";

export type RelationshipMood =
  | "clean"
  | "warm"
  | "cold"
  | "sexy"
  | "innocent"
  | "confident"
  | "mature";

export type RelationshipFace =
  | "soft"
  | "sharp"
  | "round"
  | "long"
  | "balanced";

export type RelationshipBody =
  | "slim"
  | "balanced"
  | "athletic"
  | "voluminous";

export type RelationshipStyle =
  | "casual"
  | "office"
  | "minimal"
  | "luxury"
  | "sporty"
  | "romantic";

export type RelationshipEnergy =
  | "calm"
  | "active"
  | "dominant"
  | "gentle"
  | "mysterious";

export type RelationshipModel = {
  id: string;
  gender: RelationshipGender;
  path: string;
  mood: RelationshipMood;
  face: RelationshipFace;
  body: RelationshipBody;
  style: RelationshipStyle;
  energy: RelationshipEnergy;
};

export type RelationshipVisualProfile = Partial<
  Pick<
    RelationshipModel,
    "gender" | "mood" | "face" | "body" | "style" | "energy"
  >
>;

export const maleRelationshipModels: RelationshipModel[] = [
  {
    id: "m001",
    gender: "male",
    path: "/relationship-models/male/m001.webp",
    mood: "clean",
    face: "sharp",
    body: "athletic",
    style: "office",
    energy: "gentle",
  },
  {
    id: "m002",
    gender: "male",
    path: "/relationship-models/male/m002.webp",
    mood: "warm",
    face: "long",
    body: "balanced",
    style: "casual",
    energy: "calm",
  },
  {
    id: "m003",
    gender: "male",
    path: "/relationship-models/male/m003.webp",
    mood: "cold",
    face: "soft",
    body: "slim",
    style: "romantic",
    energy: "dominant",
  },
  {
    id: "m004",
    gender: "male",
    path: "/relationship-models/male/m004.webp",
    mood: "sexy",
    face: "round",
    body: "voluminous",
    style: "sporty",
    energy: "mysterious",
  },
  {
    id: "m005",
    gender: "male",
    path: "/relationship-models/male/m005.webp",
    mood: "innocent",
    face: "balanced",
    body: "athletic",
    style: "luxury",
    energy: "active",
  },
  {
    id: "m006",
    gender: "male",
    path: "/relationship-models/male/m006.webp",
    mood: "confident",
    face: "sharp",
    body: "balanced",
    style: "minimal",
    energy: "gentle",
  },
  {
    id: "m007",
    gender: "male",
    path: "/relationship-models/male/m007.webp",
    mood: "mature",
    face: "long",
    body: "slim",
    style: "office",
    energy: "calm",
  },
  {
    id: "m008",
    gender: "male",
    path: "/relationship-models/male/m008.webp",
    mood: "clean",
    face: "soft",
    body: "voluminous",
    style: "casual",
    energy: "dominant",
  },
  {
    id: "m009",
    gender: "male",
    path: "/relationship-models/male/m009.webp",
    mood: "warm",
    face: "round",
    body: "athletic",
    style: "romantic",
    energy: "mysterious",
  },
  {
    id: "m010",
    gender: "male",
    path: "/relationship-models/male/m010.webp",
    mood: "cold",
    face: "balanced",
    body: "balanced",
    style: "sporty",
    energy: "active",
  },
  {
    id: "m011",
    gender: "male",
    path: "/relationship-models/male/m011.webp",
    mood: "sexy",
    face: "sharp",
    body: "slim",
    style: "luxury",
    energy: "gentle",
  },
  {
    id: "m012",
    gender: "male",
    path: "/relationship-models/male/m012.webp",
    mood: "innocent",
    face: "long",
    body: "voluminous",
    style: "minimal",
    energy: "calm",
  },
  {
    id: "m013",
    gender: "male",
    path: "/relationship-models/male/m013.webp",
    mood: "confident",
    face: "soft",
    body: "athletic",
    style: "office",
    energy: "dominant",
  },
  {
    id: "m014",
    gender: "male",
    path: "/relationship-models/male/m014.webp",
    mood: "mature",
    face: "round",
    body: "balanced",
    style: "casual",
    energy: "mysterious",
  },
  {
    id: "m015",
    gender: "male",
    path: "/relationship-models/male/m015.webp",
    mood: "clean",
    face: "balanced",
    body: "slim",
    style: "romantic",
    energy: "active",
  },
  {
    id: "m016",
    gender: "male",
    path: "/relationship-models/male/m016.webp",
    mood: "warm",
    face: "sharp",
    body: "voluminous",
    style: "sporty",
    energy: "gentle",
  },
  {
    id: "m017",
    gender: "male",
    path: "/relationship-models/male/m017.webp",
    mood: "cold",
    face: "long",
    body: "athletic",
    style: "luxury",
    energy: "calm",
  },
  {
    id: "m018",
    gender: "male",
    path: "/relationship-models/male/m018.webp",
    mood: "sexy",
    face: "soft",
    body: "balanced",
    style: "minimal",
    energy: "dominant",
  },
  {
    id: "m019",
    gender: "male",
    path: "/relationship-models/male/m019.webp",
    mood: "innocent",
    face: "round",
    body: "slim",
    style: "office",
    energy: "mysterious",
  },
  {
    id: "m020",
    gender: "male",
    path: "/relationship-models/male/m020.webp",
    mood: "confident",
    face: "balanced",
    body: "voluminous",
    style: "casual",
    energy: "active",
  },
  {
    id: "m021",
    gender: "male",
    path: "/relationship-models/male/m021.webp",
    mood: "mature",
    face: "sharp",
    body: "athletic",
    style: "romantic",
    energy: "gentle",
  },
  {
    id: "m022",
    gender: "male",
    path: "/relationship-models/male/m022.webp",
    mood: "clean",
    face: "long",
    body: "balanced",
    style: "sporty",
    energy: "calm",
  },
  {
    id: "m023",
    gender: "male",
    path: "/relationship-models/male/m023.webp",
    mood: "warm",
    face: "soft",
    body: "slim",
    style: "luxury",
    energy: "dominant",
  },
  {
    id: "m024",
    gender: "male",
    path: "/relationship-models/male/m024.webp",
    mood: "cold",
    face: "round",
    body: "voluminous",
    style: "minimal",
    energy: "mysterious",
  },
  {
    id: "m025",
    gender: "male",
    path: "/relationship-models/male/m025.webp",
    mood: "sexy",
    face: "balanced",
    body: "athletic",
    style: "office",
    energy: "active",
  },
  {
    id: "m026",
    gender: "male",
    path: "/relationship-models/male/m026.webp",
    mood: "innocent",
    face: "sharp",
    body: "balanced",
    style: "casual",
    energy: "gentle",
  },
  {
    id: "m027",
    gender: "male",
    path: "/relationship-models/male/m027.webp",
    mood: "confident",
    face: "long",
    body: "slim",
    style: "romantic",
    energy: "calm",
  },
  {
    id: "m028",
    gender: "male",
    path: "/relationship-models/male/m028.webp",
    mood: "mature",
    face: "soft",
    body: "voluminous",
    style: "sporty",
    energy: "dominant",
  },
  {
    id: "m029",
    gender: "male",
    path: "/relationship-models/male/m029.webp",
    mood: "clean",
    face: "round",
    body: "athletic",
    style: "luxury",
    energy: "mysterious",
  },
  {
    id: "m030",
    gender: "male",
    path: "/relationship-models/male/m030.webp",
    mood: "warm",
    face: "balanced",
    body: "balanced",
    style: "minimal",
    energy: "active",
  },
  {
    id: "m031",
    gender: "male",
    path: "/relationship-models/male/m031.webp",
    mood: "cold",
    face: "sharp",
    body: "slim",
    style: "office",
    energy: "gentle",
  },
  {
    id: "m032",
    gender: "male",
    path: "/relationship-models/male/m032.webp",
    mood: "sexy",
    face: "long",
    body: "voluminous",
    style: "casual",
    energy: "calm",
  },
  {
    id: "m033",
    gender: "male",
    path: "/relationship-models/male/m033.webp",
    mood: "innocent",
    face: "soft",
    body: "athletic",
    style: "romantic",
    energy: "dominant",
  },
  {
    id: "m034",
    gender: "male",
    path: "/relationship-models/male/m034.webp",
    mood: "confident",
    face: "round",
    body: "balanced",
    style: "sporty",
    energy: "mysterious",
  },
  {
    id: "m035",
    gender: "male",
    path: "/relationship-models/male/m035.webp",
    mood: "mature",
    face: "balanced",
    body: "slim",
    style: "luxury",
    energy: "active",
  },
  {
    id: "m036",
    gender: "male",
    path: "/relationship-models/male/m036.webp",
    mood: "clean",
    face: "sharp",
    body: "voluminous",
    style: "minimal",
    energy: "gentle",
  },
  {
    id: "m037",
    gender: "male",
    path: "/relationship-models/male/m037.webp",
    mood: "warm",
    face: "long",
    body: "athletic",
    style: "office",
    energy: "calm",
  },
  {
    id: "m038",
    gender: "male",
    path: "/relationship-models/male/m038.webp",
    mood: "cold",
    face: "soft",
    body: "balanced",
    style: "casual",
    energy: "dominant",
  },
  {
    id: "m039",
    gender: "male",
    path: "/relationship-models/male/m039.webp",
    mood: "sexy",
    face: "round",
    body: "slim",
    style: "romantic",
    energy: "mysterious",
  },
  {
    id: "m040",
    gender: "male",
    path: "/relationship-models/male/m040.webp",
    mood: "innocent",
    face: "balanced",
    body: "voluminous",
    style: "sporty",
    energy: "active",
  },
  {
    id: "m041",
    gender: "male",
    path: "/relationship-models/male/m041.webp",
    mood: "confident",
    face: "sharp",
    body: "athletic",
    style: "luxury",
    energy: "gentle",
  },
  {
    id: "m042",
    gender: "male",
    path: "/relationship-models/male/m042.webp",
    mood: "mature",
    face: "long",
    body: "balanced",
    style: "minimal",
    energy: "calm",
  },
  {
    id: "m043",
    gender: "male",
    path: "/relationship-models/male/m043.webp",
    mood: "clean",
    face: "soft",
    body: "slim",
    style: "office",
    energy: "dominant",
  },
  {
    id: "m044",
    gender: "male",
    path: "/relationship-models/male/m044.webp",
    mood: "warm",
    face: "round",
    body: "voluminous",
    style: "casual",
    energy: "mysterious",
  },
  {
    id: "m045",
    gender: "male",
    path: "/relationship-models/male/m045.webp",
    mood: "cold",
    face: "balanced",
    body: "athletic",
    style: "romantic",
    energy: "active",
  },
  {
    id: "m046",
    gender: "male",
    path: "/relationship-models/male/m046.webp",
    mood: "sexy",
    face: "sharp",
    body: "balanced",
    style: "sporty",
    energy: "gentle",
  },
  {
    id: "m047",
    gender: "male",
    path: "/relationship-models/male/m047.webp",
    mood: "innocent",
    face: "long",
    body: "slim",
    style: "luxury",
    energy: "calm",
  },
  {
    id: "m048",
    gender: "male",
    path: "/relationship-models/male/m048.webp",
    mood: "confident",
    face: "soft",
    body: "voluminous",
    style: "minimal",
    energy: "dominant",
  },
  {
    id: "m049",
    gender: "male",
    path: "/relationship-models/male/m049.webp",
    mood: "mature",
    face: "round",
    body: "athletic",
    style: "office",
    energy: "mysterious",
  },
  {
    id: "m050",
    gender: "male",
    path: "/relationship-models/male/m050.webp",
    mood: "clean",
    face: "balanced",
    body: "balanced",
    style: "casual",
    energy: "active",
  },
  {
    id: "m051",
    gender: "male",
    path: "/relationship-models/male/m051.webp",
    mood: "warm",
    face: "sharp",
    body: "slim",
    style: "romantic",
    energy: "gentle",
  },
  {
    id: "m052",
    gender: "male",
    path: "/relationship-models/male/m052.webp",
    mood: "cold",
    face: "long",
    body: "voluminous",
    style: "sporty",
    energy: "calm",
  },
  {
    id: "m053",
    gender: "male",
    path: "/relationship-models/male/m053.webp",
    mood: "sexy",
    face: "soft",
    body: "athletic",
    style: "luxury",
    energy: "dominant",
  },
  {
    id: "m054",
    gender: "male",
    path: "/relationship-models/male/m054.webp",
    mood: "innocent",
    face: "round",
    body: "balanced",
    style: "minimal",
    energy: "mysterious",
  },
  {
    id: "m055",
    gender: "male",
    path: "/relationship-models/male/m055.webp",
    mood: "confident",
    face: "balanced",
    body: "slim",
    style: "office",
    energy: "active",
  },
  {
    id: "m056",
    gender: "male",
    path: "/relationship-models/male/m056.webp",
    mood: "mature",
    face: "sharp",
    body: "voluminous",
    style: "casual",
    energy: "gentle",
  },
  {
    id: "m057",
    gender: "male",
    path: "/relationship-models/male/m057.webp",
    mood: "clean",
    face: "long",
    body: "athletic",
    style: "romantic",
    energy: "calm",
  },
  {
    id: "m058",
    gender: "male",
    path: "/relationship-models/male/m058.webp",
    mood: "warm",
    face: "soft",
    body: "balanced",
    style: "sporty",
    energy: "dominant",
  },
  {
    id: "m059",
    gender: "male",
    path: "/relationship-models/male/m059.webp",
    mood: "cold",
    face: "round",
    body: "slim",
    style: "luxury",
    energy: "mysterious",
  },
  {
    id: "m060",
    gender: "male",
    path: "/relationship-models/male/m060.webp",
    mood: "sexy",
    face: "balanced",
    body: "voluminous",
    style: "minimal",
    energy: "active",
  },
  {
    id: "m061",
    gender: "male",
    path: "/relationship-models/male/m061.webp",
    mood: "innocent",
    face: "sharp",
    body: "athletic",
    style: "office",
    energy: "gentle",
  },
  {
    id: "m062",
    gender: "male",
    path: "/relationship-models/male/m062.webp",
    mood: "confident",
    face: "long",
    body: "balanced",
    style: "casual",
    energy: "calm",
  },
  {
    id: "m063",
    gender: "male",
    path: "/relationship-models/male/m063.webp",
    mood: "mature",
    face: "soft",
    body: "slim",
    style: "romantic",
    energy: "dominant",
  },
  {
    id: "m064",
    gender: "male",
    path: "/relationship-models/male/m064.webp",
    mood: "clean",
    face: "round",
    body: "voluminous",
    style: "sporty",
    energy: "mysterious",
  },
  {
    id: "m065",
    gender: "male",
    path: "/relationship-models/male/m065.webp",
    mood: "warm",
    face: "balanced",
    body: "athletic",
    style: "luxury",
    energy: "active",
  },
  {
    id: "m066",
    gender: "male",
    path: "/relationship-models/male/m066.webp",
    mood: "cold",
    face: "sharp",
    body: "balanced",
    style: "minimal",
    energy: "gentle",
  },
  {
    id: "m067",
    gender: "male",
    path: "/relationship-models/male/m067.webp",
    mood: "sexy",
    face: "long",
    body: "slim",
    style: "office",
    energy: "calm",
  },
  {
    id: "m068",
    gender: "male",
    path: "/relationship-models/male/m068.webp",
    mood: "innocent",
    face: "soft",
    body: "voluminous",
    style: "casual",
    energy: "dominant",
  },
  {
    id: "m069",
    gender: "male",
    path: "/relationship-models/male/m069.webp",
    mood: "confident",
    face: "round",
    body: "athletic",
    style: "romantic",
    energy: "mysterious",
  },
  {
    id: "m070",
    gender: "male",
    path: "/relationship-models/male/m070.webp",
    mood: "mature",
    face: "balanced",
    body: "balanced",
    style: "sporty",
    energy: "active",
  },
  {
    id: "m071",
    gender: "male",
    path: "/relationship-models/male/m071.webp",
    mood: "clean",
    face: "sharp",
    body: "slim",
    style: "luxury",
    energy: "gentle",
  },
  {
    id: "m072",
    gender: "male",
    path: "/relationship-models/male/m072.webp",
    mood: "warm",
    face: "long",
    body: "voluminous",
    style: "minimal",
    energy: "calm",
  },
  {
    id: "m073",
    gender: "male",
    path: "/relationship-models/male/m073.webp",
    mood: "cold",
    face: "soft",
    body: "athletic",
    style: "office",
    energy: "dominant",
  },
  {
    id: "m074",
    gender: "male",
    path: "/relationship-models/male/m074.webp",
    mood: "sexy",
    face: "round",
    body: "balanced",
    style: "casual",
    energy: "mysterious",
  },
  {
    id: "m075",
    gender: "male",
    path: "/relationship-models/male/m075.webp",
    mood: "innocent",
    face: "balanced",
    body: "slim",
    style: "romantic",
    energy: "active",
  },
  {
    id: "m076",
    gender: "male",
    path: "/relationship-models/male/m076.webp",
    mood: "confident",
    face: "sharp",
    body: "voluminous",
    style: "sporty",
    energy: "gentle",
  },
  {
    id: "m077",
    gender: "male",
    path: "/relationship-models/male/m077.webp",
    mood: "mature",
    face: "long",
    body: "athletic",
    style: "luxury",
    energy: "calm",
  },
  {
    id: "m078",
    gender: "male",
    path: "/relationship-models/male/m078.webp",
    mood: "clean",
    face: "soft",
    body: "balanced",
    style: "minimal",
    energy: "dominant",
  },
  {
    id: "m079",
    gender: "male",
    path: "/relationship-models/male/m079.webp",
    mood: "warm",
    face: "round",
    body: "slim",
    style: "office",
    energy: "mysterious",
  },
  {
    id: "m080",
    gender: "male",
    path: "/relationship-models/male/m080.webp",
    mood: "cold",
    face: "balanced",
    body: "voluminous",
    style: "casual",
    energy: "active",
  },
  {
    id: "m081",
    gender: "male",
    path: "/relationship-models/male/m081.webp",
    mood: "sexy",
    face: "sharp",
    body: "athletic",
    style: "romantic",
    energy: "gentle",
  },
  {
    id: "m082",
    gender: "male",
    path: "/relationship-models/male/m082.webp",
    mood: "innocent",
    face: "long",
    body: "balanced",
    style: "sporty",
    energy: "calm",
  },
  {
    id: "m083",
    gender: "male",
    path: "/relationship-models/male/m083.webp",
    mood: "confident",
    face: "soft",
    body: "slim",
    style: "luxury",
    energy: "dominant",
  },
  {
    id: "m084",
    gender: "male",
    path: "/relationship-models/male/m084.webp",
    mood: "mature",
    face: "round",
    body: "voluminous",
    style: "minimal",
    energy: "mysterious",
  },
  {
    id: "m085",
    gender: "male",
    path: "/relationship-models/male/m085.webp",
    mood: "clean",
    face: "balanced",
    body: "athletic",
    style: "office",
    energy: "active",
  },
  {
    id: "m086",
    gender: "male",
    path: "/relationship-models/male/m086.webp",
    mood: "warm",
    face: "sharp",
    body: "balanced",
    style: "casual",
    energy: "gentle",
  },
  {
    id: "m087",
    gender: "male",
    path: "/relationship-models/male/m087.webp",
    mood: "cold",
    face: "long",
    body: "slim",
    style: "romantic",
    energy: "calm",
  },
  {
    id: "m088",
    gender: "male",
    path: "/relationship-models/male/m088.webp",
    mood: "sexy",
    face: "soft",
    body: "voluminous",
    style: "sporty",
    energy: "dominant",
  },
  {
    id: "m089",
    gender: "male",
    path: "/relationship-models/male/m089.webp",
    mood: "innocent",
    face: "round",
    body: "athletic",
    style: "luxury",
    energy: "mysterious",
  },
  {
    id: "m090",
    gender: "male",
    path: "/relationship-models/male/m090.webp",
    mood: "confident",
    face: "balanced",
    body: "balanced",
    style: "minimal",
    energy: "active",
  },
  {
    id: "m091",
    gender: "male",
    path: "/relationship-models/male/m091.webp",
    mood: "mature",
    face: "sharp",
    body: "slim",
    style: "office",
    energy: "gentle",
  },
  {
    id: "m092",
    gender: "male",
    path: "/relationship-models/male/m092.webp",
    mood: "clean",
    face: "long",
    body: "voluminous",
    style: "casual",
    energy: "calm",
  },
  {
    id: "m093",
    gender: "male",
    path: "/relationship-models/male/m093.webp",
    mood: "warm",
    face: "soft",
    body: "athletic",
    style: "romantic",
    energy: "dominant",
  },
  {
    id: "m094",
    gender: "male",
    path: "/relationship-models/male/m094.webp",
    mood: "cold",
    face: "round",
    body: "balanced",
    style: "sporty",
    energy: "mysterious",
  },
  {
    id: "m095",
    gender: "male",
    path: "/relationship-models/male/m095.webp",
    mood: "sexy",
    face: "balanced",
    body: "slim",
    style: "luxury",
    energy: "active",
  },
  {
    id: "m096",
    gender: "male",
    path: "/relationship-models/male/m096.webp",
    mood: "innocent",
    face: "sharp",
    body: "voluminous",
    style: "minimal",
    energy: "gentle",
  },
  {
    id: "m097",
    gender: "male",
    path: "/relationship-models/male/m097.webp",
    mood: "confident",
    face: "long",
    body: "athletic",
    style: "office",
    energy: "calm",
  },
  {
    id: "m098",
    gender: "male",
    path: "/relationship-models/male/m098.webp",
    mood: "mature",
    face: "soft",
    body: "balanced",
    style: "casual",
    energy: "dominant",
  },
  {
    id: "m099",
    gender: "male",
    path: "/relationship-models/male/m099.webp",
    mood: "clean",
    face: "round",
    body: "slim",
    style: "romantic",
    energy: "mysterious",
  },
  {
    id: "m100",
    gender: "male",
    path: "/relationship-models/male/m100.webp",
    mood: "warm",
    face: "balanced",
    body: "voluminous",
    style: "sporty",
    energy: "active",
  },
  {
    id: "m101",
    gender: "male",
    path: "/relationship-models/male/m101.webp",
    mood: "cold",
    face: "sharp",
    body: "athletic",
    style: "luxury",
    energy: "gentle",
  },
  {
    id: "m102",
    gender: "male",
    path: "/relationship-models/male/m102.webp",
    mood: "sexy",
    face: "long",
    body: "balanced",
    style: "minimal",
    energy: "calm",
  },
  {
    id: "m103",
    gender: "male",
    path: "/relationship-models/male/m103.webp",
    mood: "innocent",
    face: "soft",
    body: "slim",
    style: "office",
    energy: "dominant",
  },
  {
    id: "m104",
    gender: "male",
    path: "/relationship-models/male/m104.webp",
    mood: "confident",
    face: "round",
    body: "voluminous",
    style: "casual",
    energy: "mysterious",
  },
  {
    id: "m105",
    gender: "male",
    path: "/relationship-models/male/m105.webp",
    mood: "mature",
    face: "balanced",
    body: "athletic",
    style: "romantic",
    energy: "active",
  },
  {
    id: "m106",
    gender: "male",
    path: "/relationship-models/male/m106.webp",
    mood: "clean",
    face: "sharp",
    body: "balanced",
    style: "sporty",
    energy: "gentle",
  },
  {
    id: "m107",
    gender: "male",
    path: "/relationship-models/male/m107.webp",
    mood: "warm",
    face: "long",
    body: "slim",
    style: "luxury",
    energy: "calm",
  },
  {
    id: "m108",
    gender: "male",
    path: "/relationship-models/male/m108.webp",
    mood: "cold",
    face: "soft",
    body: "voluminous",
    style: "minimal",
    energy: "dominant",
  },
  {
    id: "m109",
    gender: "male",
    path: "/relationship-models/male/m109.webp",
    mood: "sexy",
    face: "round",
    body: "athletic",
    style: "office",
    energy: "mysterious",
  },
  {
    id: "m110",
    gender: "male",
    path: "/relationship-models/male/m110.webp",
    mood: "innocent",
    face: "balanced",
    body: "balanced",
    style: "casual",
    energy: "active",
  },
  {
    id: "m111",
    gender: "male",
    path: "/relationship-models/male/m111.webp",
    mood: "confident",
    face: "sharp",
    body: "slim",
    style: "romantic",
    energy: "gentle",
  },
  {
    id: "m112",
    gender: "male",
    path: "/relationship-models/male/m112.webp",
    mood: "mature",
    face: "long",
    body: "voluminous",
    style: "sporty",
    energy: "calm",
  },
  {
    id: "m113",
    gender: "male",
    path: "/relationship-models/male/m113.webp",
    mood: "clean",
    face: "soft",
    body: "athletic",
    style: "luxury",
    energy: "dominant",
  },
  {
    id: "m114",
    gender: "male",
    path: "/relationship-models/male/m114.webp",
    mood: "warm",
    face: "round",
    body: "balanced",
    style: "minimal",
    energy: "mysterious",
  },
  {
    id: "m115",
    gender: "male",
    path: "/relationship-models/male/m115.webp",
    mood: "cold",
    face: "balanced",
    body: "slim",
    style: "office",
    energy: "active",
  },
  {
    id: "m116",
    gender: "male",
    path: "/relationship-models/male/m116.webp",
    mood: "sexy",
    face: "sharp",
    body: "voluminous",
    style: "casual",
    energy: "gentle",
  },
  {
    id: "m117",
    gender: "male",
    path: "/relationship-models/male/m117.webp",
    mood: "innocent",
    face: "long",
    body: "athletic",
    style: "romantic",
    energy: "calm",
  },
  {
    id: "m118",
    gender: "male",
    path: "/relationship-models/male/m118.webp",
    mood: "confident",
    face: "soft",
    body: "balanced",
    style: "sporty",
    energy: "dominant",
  },
  {
    id: "m119",
    gender: "male",
    path: "/relationship-models/male/m119.webp",
    mood: "mature",
    face: "round",
    body: "slim",
    style: "luxury",
    energy: "mysterious",
  },
  {
    id: "m120",
    gender: "male",
    path: "/relationship-models/male/m120.webp",
    mood: "clean",
    face: "balanced",
    body: "voluminous",
    style: "minimal",
    energy: "active",
  },
  {
    id: "m121",
    gender: "male",
    path: "/relationship-models/male/m121.webp",
    mood: "warm",
    face: "sharp",
    body: "athletic",
    style: "office",
    energy: "gentle",
  },
  {
    id: "m122",
    gender: "male",
    path: "/relationship-models/male/m122.webp",
    mood: "cold",
    face: "long",
    body: "balanced",
    style: "casual",
    energy: "calm",
  },
  {
    id: "m123",
    gender: "male",
    path: "/relationship-models/male/m123.webp",
    mood: "sexy",
    face: "soft",
    body: "slim",
    style: "romantic",
    energy: "dominant",
  },
  {
    id: "m124",
    gender: "male",
    path: "/relationship-models/male/m124.webp",
    mood: "innocent",
    face: "round",
    body: "voluminous",
    style: "sporty",
    energy: "mysterious",
  },
  {
    id: "m125",
    gender: "male",
    path: "/relationship-models/male/m125.webp",
    mood: "confident",
    face: "balanced",
    body: "athletic",
    style: "luxury",
    energy: "active",
  },
  {
    id: "m126",
    gender: "male",
    path: "/relationship-models/male/m126.webp",
    mood: "mature",
    face: "sharp",
    body: "balanced",
    style: "minimal",
    energy: "gentle",
  },
  {
    id: "m127",
    gender: "male",
    path: "/relationship-models/male/m127.webp",
    mood: "clean",
    face: "long",
    body: "slim",
    style: "office",
    energy: "calm",
  },
  {
    id: "m128",
    gender: "male",
    path: "/relationship-models/male/m128.webp",
    mood: "warm",
    face: "soft",
    body: "voluminous",
    style: "casual",
    energy: "dominant",
  },
  {
    id: "m129",
    gender: "male",
    path: "/relationship-models/male/m129.webp",
    mood: "cold",
    face: "round",
    body: "athletic",
    style: "romantic",
    energy: "mysterious",
  },
  {
    id: "m130",
    gender: "male",
    path: "/relationship-models/male/m130.webp",
    mood: "sexy",
    face: "balanced",
    body: "balanced",
    style: "sporty",
    energy: "active",
  },
  {
    id: "m131",
    gender: "male",
    path: "/relationship-models/male/m131.webp",
    mood: "innocent",
    face: "sharp",
    body: "slim",
    style: "luxury",
    energy: "gentle",
  },
  {
    id: "m132",
    gender: "male",
    path: "/relationship-models/male/m132.webp",
    mood: "confident",
    face: "long",
    body: "voluminous",
    style: "minimal",
    energy: "calm",
  },
  {
    id: "m133",
    gender: "male",
    path: "/relationship-models/male/m133.webp",
    mood: "mature",
    face: "soft",
    body: "athletic",
    style: "office",
    energy: "dominant",
  },
  {
    id: "m134",
    gender: "male",
    path: "/relationship-models/male/m134.webp",
    mood: "clean",
    face: "round",
    body: "balanced",
    style: "casual",
    energy: "mysterious",
  },
  {
    id: "m135",
    gender: "male",
    path: "/relationship-models/male/m135.webp",
    mood: "warm",
    face: "balanced",
    body: "slim",
    style: "romantic",
    energy: "active",
  },
  {
    id: "m136",
    gender: "male",
    path: "/relationship-models/male/m136.webp",
    mood: "cold",
    face: "sharp",
    body: "voluminous",
    style: "sporty",
    energy: "gentle",
  },
  {
    id: "m137",
    gender: "male",
    path: "/relationship-models/male/m137.webp",
    mood: "sexy",
    face: "long",
    body: "athletic",
    style: "luxury",
    energy: "calm",
  },
  {
    id: "m138",
    gender: "male",
    path: "/relationship-models/male/m138.webp",
    mood: "innocent",
    face: "soft",
    body: "balanced",
    style: "minimal",
    energy: "dominant",
  },
  {
    id: "m139",
    gender: "male",
    path: "/relationship-models/male/m139.webp",
    mood: "confident",
    face: "round",
    body: "slim",
    style: "office",
    energy: "mysterious",
  },
  {
    id: "m140",
    gender: "male",
    path: "/relationship-models/male/m140.webp",
    mood: "mature",
    face: "balanced",
    body: "voluminous",
    style: "casual",
    energy: "active",
  },
  {
    id: "m141",
    gender: "male",
    path: "/relationship-models/male/m141.webp",
    mood: "clean",
    face: "sharp",
    body: "athletic",
    style: "romantic",
    energy: "gentle",
  },
  {
    id: "m142",
    gender: "male",
    path: "/relationship-models/male/m142.webp",
    mood: "warm",
    face: "long",
    body: "balanced",
    style: "sporty",
    energy: "calm",
  },
  {
    id: "m143",
    gender: "male",
    path: "/relationship-models/male/m143.webp",
    mood: "cold",
    face: "soft",
    body: "slim",
    style: "luxury",
    energy: "dominant",
  },
  {
    id: "m144",
    gender: "male",
    path: "/relationship-models/male/m144.webp",
    mood: "sexy",
    face: "round",
    body: "voluminous",
    style: "minimal",
    energy: "mysterious",
  },
  {
    id: "m145",
    gender: "male",
    path: "/relationship-models/male/m145.webp",
    mood: "innocent",
    face: "balanced",
    body: "athletic",
    style: "office",
    energy: "active",
  },
  {
    id: "m146",
    gender: "male",
    path: "/relationship-models/male/m146.webp",
    mood: "confident",
    face: "sharp",
    body: "balanced",
    style: "casual",
    energy: "gentle",
  },
  {
    id: "m147",
    gender: "male",
    path: "/relationship-models/male/m147.webp",
    mood: "mature",
    face: "long",
    body: "slim",
    style: "romantic",
    energy: "calm",
  },
  {
    id: "m148",
    gender: "male",
    path: "/relationship-models/male/m148.webp",
    mood: "clean",
    face: "soft",
    body: "voluminous",
    style: "sporty",
    energy: "dominant",
  },
  {
    id: "m149",
    gender: "male",
    path: "/relationship-models/male/m149.webp",
    mood: "warm",
    face: "round",
    body: "athletic",
    style: "luxury",
    energy: "mysterious",
  },
  {
    id: "m150",
    gender: "male",
    path: "/relationship-models/male/m150.webp",
    mood: "cold",
    face: "balanced",
    body: "balanced",
    style: "minimal",
    energy: "active",
  },
  {
    id: "m151",
    gender: "male",
    path: "/relationship-models/male/m151.webp",
    mood: "sexy",
    face: "sharp",
    body: "slim",
    style: "office",
    energy: "gentle",
  },
  {
    id: "m152",
    gender: "male",
    path: "/relationship-models/male/m152.webp",
    mood: "innocent",
    face: "long",
    body: "voluminous",
    style: "casual",
    energy: "calm",
  },
  {
    id: "m153",
    gender: "male",
    path: "/relationship-models/male/m153.webp",
    mood: "confident",
    face: "soft",
    body: "athletic",
    style: "romantic",
    energy: "dominant",
  },
  {
    id: "m154",
    gender: "male",
    path: "/relationship-models/male/m154.webp",
    mood: "mature",
    face: "round",
    body: "balanced",
    style: "sporty",
    energy: "mysterious",
  },
  {
    id: "m155",
    gender: "male",
    path: "/relationship-models/male/m155.webp",
    mood: "clean",
    face: "balanced",
    body: "slim",
    style: "luxury",
    energy: "active",
  },
  {
    id: "m156",
    gender: "male",
    path: "/relationship-models/male/m156.webp",
    mood: "warm",
    face: "sharp",
    body: "voluminous",
    style: "minimal",
    energy: "gentle",
  },
  {
    id: "m157",
    gender: "male",
    path: "/relationship-models/male/m157.webp",
    mood: "cold",
    face: "long",
    body: "athletic",
    style: "office",
    energy: "calm",
  },
  {
    id: "m158",
    gender: "male",
    path: "/relationship-models/male/m158.webp",
    mood: "sexy",
    face: "soft",
    body: "balanced",
    style: "casual",
    energy: "dominant",
  },
  {
    id: "m159",
    gender: "male",
    path: "/relationship-models/male/m159.webp",
    mood: "innocent",
    face: "round",
    body: "slim",
    style: "romantic",
    energy: "mysterious",
  },
  {
    id: "m160",
    gender: "male",
    path: "/relationship-models/male/m160.webp",
    mood: "confident",
    face: "balanced",
    body: "voluminous",
    style: "sporty",
    energy: "active",
  },
  {
    id: "m161",
    gender: "male",
    path: "/relationship-models/male/m161.webp",
    mood: "mature",
    face: "sharp",
    body: "athletic",
    style: "luxury",
    energy: "gentle",
  },
  {
    id: "m162",
    gender: "male",
    path: "/relationship-models/male/m162.webp",
    mood: "clean",
    face: "long",
    body: "balanced",
    style: "minimal",
    energy: "calm",
  },
  {
    id: "m163",
    gender: "male",
    path: "/relationship-models/male/m163.webp",
    mood: "warm",
    face: "soft",
    body: "slim",
    style: "office",
    energy: "dominant",
  },
  {
    id: "m164",
    gender: "male",
    path: "/relationship-models/male/m164.webp",
    mood: "cold",
    face: "round",
    body: "voluminous",
    style: "casual",
    energy: "mysterious",
  },
  {
    id: "m165",
    gender: "male",
    path: "/relationship-models/male/m165.webp",
    mood: "sexy",
    face: "balanced",
    body: "athletic",
    style: "romantic",
    energy: "active",
  },
  {
    id: "m166",
    gender: "male",
    path: "/relationship-models/male/m166.webp",
    mood: "innocent",
    face: "sharp",
    body: "balanced",
    style: "sporty",
    energy: "gentle",
  },
  {
    id: "m167",
    gender: "male",
    path: "/relationship-models/male/m167.webp",
    mood: "confident",
    face: "long",
    body: "slim",
    style: "luxury",
    energy: "calm",
  },
  {
    id: "m168",
    gender: "male",
    path: "/relationship-models/male/m168.webp",
    mood: "mature",
    face: "soft",
    body: "voluminous",
    style: "minimal",
    energy: "dominant",
  },
  {
    id: "m169",
    gender: "male",
    path: "/relationship-models/male/m169.webp",
    mood: "clean",
    face: "round",
    body: "athletic",
    style: "office",
    energy: "mysterious",
  },
  {
    id: "m170",
    gender: "male",
    path: "/relationship-models/male/m170.webp",
    mood: "warm",
    face: "balanced",
    body: "balanced",
    style: "casual",
    energy: "active",
  },
  {
    id: "m171",
    gender: "male",
    path: "/relationship-models/male/m171.webp",
    mood: "cold",
    face: "sharp",
    body: "slim",
    style: "romantic",
    energy: "gentle",
  },
  {
    id: "m172",
    gender: "male",
    path: "/relationship-models/male/m172.webp",
    mood: "sexy",
    face: "long",
    body: "voluminous",
    style: "sporty",
    energy: "calm",
  },
  {
    id: "m173",
    gender: "male",
    path: "/relationship-models/male/m173.webp",
    mood: "innocent",
    face: "soft",
    body: "athletic",
    style: "luxury",
    energy: "dominant",
  },
  {
    id: "m174",
    gender: "male",
    path: "/relationship-models/male/m174.webp",
    mood: "confident",
    face: "round",
    body: "balanced",
    style: "minimal",
    energy: "mysterious",
  },
  {
    id: "m175",
    gender: "male",
    path: "/relationship-models/male/m175.webp",
    mood: "mature",
    face: "balanced",
    body: "slim",
    style: "office",
    energy: "active",
  },
  {
    id: "m176",
    gender: "male",
    path: "/relationship-models/male/m176.webp",
    mood: "clean",
    face: "sharp",
    body: "voluminous",
    style: "casual",
    energy: "gentle",
  },
  {
    id: "m177",
    gender: "male",
    path: "/relationship-models/male/m177.webp",
    mood: "warm",
    face: "long",
    body: "athletic",
    style: "romantic",
    energy: "calm",
  },
  {
    id: "m178",
    gender: "male",
    path: "/relationship-models/male/m178.webp",
    mood: "cold",
    face: "soft",
    body: "balanced",
    style: "sporty",
    energy: "dominant",
  },
  {
    id: "m179",
    gender: "male",
    path: "/relationship-models/male/m179.webp",
    mood: "sexy",
    face: "round",
    body: "slim",
    style: "luxury",
    energy: "mysterious",
  },
  {
    id: "m180",
    gender: "male",
    path: "/relationship-models/male/m180.webp",
    mood: "innocent",
    face: "balanced",
    body: "voluminous",
    style: "minimal",
    energy: "active",
  },
  {
    id: "m181",
    gender: "male",
    path: "/relationship-models/male/m181.webp",
    mood: "confident",
    face: "sharp",
    body: "athletic",
    style: "office",
    energy: "gentle",
  },
  {
    id: "m182",
    gender: "male",
    path: "/relationship-models/male/m182.webp",
    mood: "mature",
    face: "long",
    body: "balanced",
    style: "casual",
    energy: "calm",
  },
  {
    id: "m183",
    gender: "male",
    path: "/relationship-models/male/m183.webp",
    mood: "clean",
    face: "soft",
    body: "slim",
    style: "romantic",
    energy: "dominant",
  },
  {
    id: "m184",
    gender: "male",
    path: "/relationship-models/male/m184.webp",
    mood: "warm",
    face: "round",
    body: "voluminous",
    style: "sporty",
    energy: "mysterious",
  },
  {
    id: "m185",
    gender: "male",
    path: "/relationship-models/male/m185.webp",
    mood: "cold",
    face: "balanced",
    body: "athletic",
    style: "luxury",
    energy: "active",
  },
  {
    id: "m186",
    gender: "male",
    path: "/relationship-models/male/m186.webp",
    mood: "sexy",
    face: "sharp",
    body: "balanced",
    style: "minimal",
    energy: "gentle",
  },
  {
    id: "m187",
    gender: "male",
    path: "/relationship-models/male/m187.webp",
    mood: "innocent",
    face: "long",
    body: "slim",
    style: "office",
    energy: "calm",
  },
  {
    id: "m188",
    gender: "male",
    path: "/relationship-models/male/m188.webp",
    mood: "confident",
    face: "soft",
    body: "voluminous",
    style: "casual",
    energy: "dominant",
  },
  {
    id: "m189",
    gender: "male",
    path: "/relationship-models/male/m189.webp",
    mood: "mature",
    face: "round",
    body: "athletic",
    style: "romantic",
    energy: "mysterious",
  },
  {
    id: "m190",
    gender: "male",
    path: "/relationship-models/male/m190.webp",
    mood: "clean",
    face: "balanced",
    body: "balanced",
    style: "sporty",
    energy: "active",
  },
  {
    id: "m191",
    gender: "male",
    path: "/relationship-models/male/m191.webp",
    mood: "warm",
    face: "sharp",
    body: "slim",
    style: "luxury",
    energy: "gentle",
  },
  {
    id: "m192",
    gender: "male",
    path: "/relationship-models/male/m192.webp",
    mood: "cold",
    face: "long",
    body: "voluminous",
    style: "minimal",
    energy: "calm",
  },
  {
    id: "m193",
    gender: "male",
    path: "/relationship-models/male/m193.webp",
    mood: "sexy",
    face: "soft",
    body: "athletic",
    style: "office",
    energy: "dominant",
  },
  {
    id: "m194",
    gender: "male",
    path: "/relationship-models/male/m194.webp",
    mood: "innocent",
    face: "round",
    body: "balanced",
    style: "casual",
    energy: "mysterious",
  },
  {
    id: "m195",
    gender: "male",
    path: "/relationship-models/male/m195.webp",
    mood: "confident",
    face: "balanced",
    body: "slim",
    style: "romantic",
    energy: "active",
  },
  {
    id: "m196",
    gender: "male",
    path: "/relationship-models/male/m196.webp",
    mood: "mature",
    face: "sharp",
    body: "voluminous",
    style: "sporty",
    energy: "gentle",
  },
  {
    id: "m197",
    gender: "male",
    path: "/relationship-models/male/m197.webp",
    mood: "clean",
    face: "long",
    body: "athletic",
    style: "luxury",
    energy: "calm",
  },
  {
    id: "m198",
    gender: "male",
    path: "/relationship-models/male/m198.webp",
    mood: "warm",
    face: "soft",
    body: "balanced",
    style: "minimal",
    energy: "dominant",
  },
  {
    id: "m199",
    gender: "male",
    path: "/relationship-models/male/m199.webp",
    mood: "cold",
    face: "round",
    body: "slim",
    style: "office",
    energy: "mysterious",
  },
  {
    id: "m200",
    gender: "male",
    path: "/relationship-models/male/m200.webp",
    mood: "sexy",
    face: "balanced",
    body: "voluminous",
    style: "casual",
    energy: "active",
  },
  {
    id: "m201",
    gender: "male",
    path: "/relationship-models/male/m201.webp",
    mood: "innocent",
    face: "sharp",
    body: "athletic",
    style: "romantic",
    energy: "gentle",
  },
  {
    id: "m202",
    gender: "male",
    path: "/relationship-models/male/m202.webp",
    mood: "confident",
    face: "long",
    body: "balanced",
    style: "sporty",
    energy: "calm",
  },
  {
    id: "m203",
    gender: "male",
    path: "/relationship-models/male/m203.webp",
    mood: "mature",
    face: "soft",
    body: "slim",
    style: "luxury",
    energy: "dominant",
  },
  {
    id: "m204",
    gender: "male",
    path: "/relationship-models/male/m204.webp",
    mood: "clean",
    face: "round",
    body: "voluminous",
    style: "minimal",
    energy: "mysterious",
  },
  {
    id: "m205",
    gender: "male",
    path: "/relationship-models/male/m205.webp",
    mood: "warm",
    face: "balanced",
    body: "athletic",
    style: "office",
    energy: "active",
  },
  {
    id: "m206",
    gender: "male",
    path: "/relationship-models/male/m206.webp",
    mood: "cold",
    face: "sharp",
    body: "balanced",
    style: "casual",
    energy: "gentle",
  },
  {
    id: "m207",
    gender: "male",
    path: "/relationship-models/male/m207.webp",
    mood: "sexy",
    face: "long",
    body: "slim",
    style: "romantic",
    energy: "calm",
  },
  {
    id: "m208",
    gender: "male",
    path: "/relationship-models/male/m208.webp",
    mood: "innocent",
    face: "soft",
    body: "voluminous",
    style: "sporty",
    energy: "dominant",
  },
  {
    id: "m209",
    gender: "male",
    path: "/relationship-models/male/m209.webp",
    mood: "confident",
    face: "round",
    body: "athletic",
    style: "luxury",
    energy: "mysterious",
  },
  {
    id: "m210",
    gender: "male",
    path: "/relationship-models/male/m210.webp",
    mood: "mature",
    face: "balanced",
    body: "balanced",
    style: "minimal",
    energy: "active",
  },
  {
    id: "m211",
    gender: "male",
    path: "/relationship-models/male/m211.webp",
    mood: "clean",
    face: "sharp",
    body: "slim",
    style: "office",
    energy: "gentle",
  },
  {
    id: "m212",
    gender: "male",
    path: "/relationship-models/male/m212.webp",
    mood: "warm",
    face: "long",
    body: "voluminous",
    style: "casual",
    energy: "calm",
  },
  {
    id: "m213",
    gender: "male",
    path: "/relationship-models/male/m213.webp",
    mood: "cold",
    face: "soft",
    body: "athletic",
    style: "romantic",
    energy: "dominant",
  },
  {
    id: "m214",
    gender: "male",
    path: "/relationship-models/male/m214.webp",
    mood: "sexy",
    face: "round",
    body: "balanced",
    style: "sporty",
    energy: "mysterious",
  },
  {
    id: "m215",
    gender: "male",
    path: "/relationship-models/male/m215.webp",
    mood: "innocent",
    face: "balanced",
    body: "slim",
    style: "luxury",
    energy: "active",
  },
  {
    id: "m216",
    gender: "male",
    path: "/relationship-models/male/m216.webp",
    mood: "confident",
    face: "sharp",
    body: "voluminous",
    style: "minimal",
    energy: "gentle",
  },
  {
    id: "m217",
    gender: "male",
    path: "/relationship-models/male/m217.webp",
    mood: "mature",
    face: "long",
    body: "athletic",
    style: "office",
    energy: "calm",
  },
  {
    id: "m218",
    gender: "male",
    path: "/relationship-models/male/m218.webp",
    mood: "clean",
    face: "soft",
    body: "balanced",
    style: "casual",
    energy: "dominant",
  },
  {
    id: "m219",
    gender: "male",
    path: "/relationship-models/male/m219.webp",
    mood: "warm",
    face: "round",
    body: "slim",
    style: "romantic",
    energy: "mysterious",
  },
  {
    id: "m220",
    gender: "male",
    path: "/relationship-models/male/m220.webp",
    mood: "cold",
    face: "balanced",
    body: "voluminous",
    style: "sporty",
    energy: "active",
  },
  {
    id: "m221",
    gender: "male",
    path: "/relationship-models/male/m221.webp",
    mood: "sexy",
    face: "sharp",
    body: "athletic",
    style: "luxury",
    energy: "gentle",
  },
  {
    id: "m222",
    gender: "male",
    path: "/relationship-models/male/m222.webp",
    mood: "innocent",
    face: "long",
    body: "balanced",
    style: "minimal",
    energy: "calm",
  },
  {
    id: "m223",
    gender: "male",
    path: "/relationship-models/male/m223.webp",
    mood: "confident",
    face: "soft",
    body: "slim",
    style: "office",
    energy: "dominant",
  },
  {
    id: "m224",
    gender: "male",
    path: "/relationship-models/male/m224.webp",
    mood: "mature",
    face: "round",
    body: "voluminous",
    style: "casual",
    energy: "mysterious",
  },
  {
    id: "m225",
    gender: "male",
    path: "/relationship-models/male/m225.webp",
    mood: "clean",
    face: "balanced",
    body: "athletic",
    style: "romantic",
    energy: "active",
  },
  {
    id: "m226",
    gender: "male",
    path: "/relationship-models/male/m226.webp",
    mood: "warm",
    face: "sharp",
    body: "balanced",
    style: "sporty",
    energy: "gentle",
  },
  {
    id: "m227",
    gender: "male",
    path: "/relationship-models/male/m227.webp",
    mood: "cold",
    face: "long",
    body: "slim",
    style: "luxury",
    energy: "calm",
  },
  {
    id: "m228",
    gender: "male",
    path: "/relationship-models/male/m228.webp",
    mood: "sexy",
    face: "soft",
    body: "voluminous",
    style: "minimal",
    energy: "dominant",
  },
  {
    id: "m229",
    gender: "male",
    path: "/relationship-models/male/m229.webp",
    mood: "innocent",
    face: "round",
    body: "athletic",
    style: "office",
    energy: "mysterious",
  },
  {
    id: "m230",
    gender: "male",
    path: "/relationship-models/male/m230.webp",
    mood: "confident",
    face: "balanced",
    body: "balanced",
    style: "casual",
    energy: "active",
  },
  {
    id: "m231",
    gender: "male",
    path: "/relationship-models/male/m231.webp",
    mood: "mature",
    face: "sharp",
    body: "slim",
    style: "romantic",
    energy: "gentle",
  },
  {
    id: "m232",
    gender: "male",
    path: "/relationship-models/male/m232.webp",
    mood: "clean",
    face: "long",
    body: "voluminous",
    style: "sporty",
    energy: "calm",
  },
  {
    id: "m233",
    gender: "male",
    path: "/relationship-models/male/m233.webp",
    mood: "warm",
    face: "soft",
    body: "athletic",
    style: "luxury",
    energy: "dominant",
  },
  {
    id: "m234",
    gender: "male",
    path: "/relationship-models/male/m234.webp",
    mood: "cold",
    face: "round",
    body: "balanced",
    style: "minimal",
    energy: "mysterious",
  },
  {
    id: "m235",
    gender: "male",
    path: "/relationship-models/male/m235.webp",
    mood: "sexy",
    face: "balanced",
    body: "slim",
    style: "office",
    energy: "active",
  },
  {
    id: "m236",
    gender: "male",
    path: "/relationship-models/male/m236.webp",
    mood: "innocent",
    face: "sharp",
    body: "voluminous",
    style: "casual",
    energy: "gentle",
  },
  {
    id: "m237",
    gender: "male",
    path: "/relationship-models/male/m237.webp",
    mood: "confident",
    face: "long",
    body: "athletic",
    style: "romantic",
    energy: "calm",
  },
  {
    id: "m238",
    gender: "male",
    path: "/relationship-models/male/m238.webp",
    mood: "mature",
    face: "soft",
    body: "balanced",
    style: "sporty",
    energy: "dominant",
  },
  {
    id: "m239",
    gender: "male",
    path: "/relationship-models/male/m239.webp",
    mood: "clean",
    face: "round",
    body: "slim",
    style: "luxury",
    energy: "mysterious",
  },
  {
    id: "m240",
    gender: "male",
    path: "/relationship-models/male/m240.webp",
    mood: "warm",
    face: "balanced",
    body: "voluminous",
    style: "minimal",
    energy: "active",
  },
  {
    id: "m241",
    gender: "male",
    path: "/relationship-models/male/m241.webp",
    mood: "cold",
    face: "sharp",
    body: "athletic",
    style: "office",
    energy: "gentle",
  },
  {
    id: "m242",
    gender: "male",
    path: "/relationship-models/male/m242.webp",
    mood: "sexy",
    face: "long",
    body: "balanced",
    style: "casual",
    energy: "calm",
  }
];

export const femaleRelationshipModels: RelationshipModel[] = [
  {
    id: "f001",
    gender: "female",
    path: "/relationship-models/female/f001.webp",
    mood: "clean",
    face: "sharp",
    body: "athletic",
    style: "office",
    energy: "gentle",
  },
  {
    id: "f002",
    gender: "female",
    path: "/relationship-models/female/f002.webp",
    mood: "warm",
    face: "long",
    body: "balanced",
    style: "casual",
    energy: "calm",
  },
  {
    id: "f003",
    gender: "female",
    path: "/relationship-models/female/f003.webp",
    mood: "cold",
    face: "soft",
    body: "slim",
    style: "romantic",
    energy: "dominant",
  },
  {
    id: "f004",
    gender: "female",
    path: "/relationship-models/female/f004.webp",
    mood: "sexy",
    face: "round",
    body: "voluminous",
    style: "sporty",
    energy: "mysterious",
  },
  {
    id: "f005",
    gender: "female",
    path: "/relationship-models/female/f005.webp",
    mood: "innocent",
    face: "balanced",
    body: "athletic",
    style: "luxury",
    energy: "active",
  },
  {
    id: "f006",
    gender: "female",
    path: "/relationship-models/female/f006.webp",
    mood: "confident",
    face: "sharp",
    body: "balanced",
    style: "minimal",
    energy: "gentle",
  },
  {
    id: "f007",
    gender: "female",
    path: "/relationship-models/female/f007.webp",
    mood: "mature",
    face: "long",
    body: "slim",
    style: "office",
    energy: "calm",
  },
  {
    id: "f008",
    gender: "female",
    path: "/relationship-models/female/f008.webp",
    mood: "clean",
    face: "soft",
    body: "voluminous",
    style: "casual",
    energy: "dominant",
  },
  {
    id: "f009",
    gender: "female",
    path: "/relationship-models/female/f009.webp",
    mood: "warm",
    face: "round",
    body: "athletic",
    style: "romantic",
    energy: "mysterious",
  },
  {
    id: "f010",
    gender: "female",
    path: "/relationship-models/female/f010.webp",
    mood: "cold",
    face: "balanced",
    body: "balanced",
    style: "sporty",
    energy: "active",
  },
  {
    id: "f011",
    gender: "female",
    path: "/relationship-models/female/f011.webp",
    mood: "sexy",
    face: "sharp",
    body: "slim",
    style: "luxury",
    energy: "gentle",
  },
  {
    id: "f012",
    gender: "female",
    path: "/relationship-models/female/f012.webp",
    mood: "innocent",
    face: "long",
    body: "voluminous",
    style: "minimal",
    energy: "calm",
  },
  {
    id: "f013",
    gender: "female",
    path: "/relationship-models/female/f013.webp",
    mood: "confident",
    face: "soft",
    body: "athletic",
    style: "office",
    energy: "dominant",
  },
  {
    id: "f014",
    gender: "female",
    path: "/relationship-models/female/f014.webp",
    mood: "mature",
    face: "round",
    body: "balanced",
    style: "casual",
    energy: "mysterious",
  },
  {
    id: "f015",
    gender: "female",
    path: "/relationship-models/female/f015.webp",
    mood: "clean",
    face: "balanced",
    body: "slim",
    style: "romantic",
    energy: "active",
  },
  {
    id: "f016",
    gender: "female",
    path: "/relationship-models/female/f016.webp",
    mood: "warm",
    face: "sharp",
    body: "voluminous",
    style: "sporty",
    energy: "gentle",
  },
  {
    id: "f017",
    gender: "female",
    path: "/relationship-models/female/f017.webp",
    mood: "cold",
    face: "long",
    body: "athletic",
    style: "luxury",
    energy: "calm",
  },
  {
    id: "f018",
    gender: "female",
    path: "/relationship-models/female/f018.webp",
    mood: "sexy",
    face: "soft",
    body: "balanced",
    style: "minimal",
    energy: "dominant",
  },
  {
    id: "f019",
    gender: "female",
    path: "/relationship-models/female/f019.webp",
    mood: "innocent",
    face: "round",
    body: "slim",
    style: "office",
    energy: "mysterious",
  },
  {
    id: "f020",
    gender: "female",
    path: "/relationship-models/female/f020.webp",
    mood: "confident",
    face: "balanced",
    body: "voluminous",
    style: "casual",
    energy: "active",
  },
  {
    id: "f021",
    gender: "female",
    path: "/relationship-models/female/f021.webp",
    mood: "mature",
    face: "sharp",
    body: "athletic",
    style: "romantic",
    energy: "gentle",
  },
  {
    id: "f022",
    gender: "female",
    path: "/relationship-models/female/f022.webp",
    mood: "clean",
    face: "long",
    body: "balanced",
    style: "sporty",
    energy: "calm",
  },
  {
    id: "f023",
    gender: "female",
    path: "/relationship-models/female/f023.webp",
    mood: "warm",
    face: "soft",
    body: "slim",
    style: "luxury",
    energy: "dominant",
  },
  {
    id: "f024",
    gender: "female",
    path: "/relationship-models/female/f024.webp",
    mood: "cold",
    face: "round",
    body: "voluminous",
    style: "minimal",
    energy: "mysterious",
  },
  {
    id: "f025",
    gender: "female",
    path: "/relationship-models/female/f025.webp",
    mood: "sexy",
    face: "balanced",
    body: "athletic",
    style: "office",
    energy: "active",
  },
  {
    id: "f026",
    gender: "female",
    path: "/relationship-models/female/f026.webp",
    mood: "innocent",
    face: "sharp",
    body: "balanced",
    style: "casual",
    energy: "gentle",
  },
  {
    id: "f027",
    gender: "female",
    path: "/relationship-models/female/f027.webp",
    mood: "confident",
    face: "long",
    body: "slim",
    style: "romantic",
    energy: "calm",
  },
  {
    id: "f028",
    gender: "female",
    path: "/relationship-models/female/f028.webp",
    mood: "mature",
    face: "soft",
    body: "voluminous",
    style: "sporty",
    energy: "dominant",
  },
  {
    id: "f029",
    gender: "female",
    path: "/relationship-models/female/f029.webp",
    mood: "clean",
    face: "round",
    body: "athletic",
    style: "luxury",
    energy: "mysterious",
  },
  {
    id: "f030",
    gender: "female",
    path: "/relationship-models/female/f030.webp",
    mood: "warm",
    face: "balanced",
    body: "balanced",
    style: "minimal",
    energy: "active",
  },
  {
    id: "f031",
    gender: "female",
    path: "/relationship-models/female/f031.webp",
    mood: "cold",
    face: "sharp",
    body: "slim",
    style: "office",
    energy: "gentle",
  },
  {
    id: "f032",
    gender: "female",
    path: "/relationship-models/female/f032.webp",
    mood: "sexy",
    face: "long",
    body: "voluminous",
    style: "casual",
    energy: "calm",
  },
  {
    id: "f033",
    gender: "female",
    path: "/relationship-models/female/f033.webp",
    mood: "innocent",
    face: "soft",
    body: "athletic",
    style: "romantic",
    energy: "dominant",
  },
  {
    id: "f034",
    gender: "female",
    path: "/relationship-models/female/f034.webp",
    mood: "confident",
    face: "round",
    body: "balanced",
    style: "sporty",
    energy: "mysterious",
  },
  {
    id: "f035",
    gender: "female",
    path: "/relationship-models/female/f035.webp",
    mood: "mature",
    face: "balanced",
    body: "slim",
    style: "luxury",
    energy: "active",
  },
  {
    id: "f036",
    gender: "female",
    path: "/relationship-models/female/f036.webp",
    mood: "clean",
    face: "sharp",
    body: "voluminous",
    style: "minimal",
    energy: "gentle",
  },
  {
    id: "f037",
    gender: "female",
    path: "/relationship-models/female/f037.webp",
    mood: "warm",
    face: "long",
    body: "athletic",
    style: "office",
    energy: "calm",
  },
  {
    id: "f038",
    gender: "female",
    path: "/relationship-models/female/f038.webp",
    mood: "cold",
    face: "soft",
    body: "balanced",
    style: "casual",
    energy: "dominant",
  },
  {
    id: "f039",
    gender: "female",
    path: "/relationship-models/female/f039.webp",
    mood: "sexy",
    face: "round",
    body: "slim",
    style: "romantic",
    energy: "mysterious",
  },
  {
    id: "f040",
    gender: "female",
    path: "/relationship-models/female/f040.webp",
    mood: "innocent",
    face: "balanced",
    body: "voluminous",
    style: "sporty",
    energy: "active",
  },
  {
    id: "f041",
    gender: "female",
    path: "/relationship-models/female/f041.webp",
    mood: "confident",
    face: "sharp",
    body: "athletic",
    style: "luxury",
    energy: "gentle",
  },
  {
    id: "f042",
    gender: "female",
    path: "/relationship-models/female/f042.webp",
    mood: "mature",
    face: "long",
    body: "balanced",
    style: "minimal",
    energy: "calm",
  },
  {
    id: "f043",
    gender: "female",
    path: "/relationship-models/female/f043.webp",
    mood: "clean",
    face: "soft",
    body: "slim",
    style: "office",
    energy: "dominant",
  },
  {
    id: "f044",
    gender: "female",
    path: "/relationship-models/female/f044.webp",
    mood: "warm",
    face: "round",
    body: "voluminous",
    style: "casual",
    energy: "mysterious",
  },
  {
    id: "f045",
    gender: "female",
    path: "/relationship-models/female/f045.webp",
    mood: "cold",
    face: "balanced",
    body: "athletic",
    style: "romantic",
    energy: "active",
  },
  {
    id: "f046",
    gender: "female",
    path: "/relationship-models/female/f046.webp",
    mood: "sexy",
    face: "sharp",
    body: "balanced",
    style: "sporty",
    energy: "gentle",
  },
  {
    id: "f047",
    gender: "female",
    path: "/relationship-models/female/f047.webp",
    mood: "innocent",
    face: "long",
    body: "slim",
    style: "luxury",
    energy: "calm",
  },
  {
    id: "f048",
    gender: "female",
    path: "/relationship-models/female/f048.webp",
    mood: "confident",
    face: "soft",
    body: "voluminous",
    style: "minimal",
    energy: "dominant",
  },
  {
    id: "f049",
    gender: "female",
    path: "/relationship-models/female/f049.webp",
    mood: "mature",
    face: "round",
    body: "athletic",
    style: "office",
    energy: "mysterious",
  },
  {
    id: "f050",
    gender: "female",
    path: "/relationship-models/female/f050.webp",
    mood: "clean",
    face: "balanced",
    body: "balanced",
    style: "casual",
    energy: "active",
  },
  {
    id: "f051",
    gender: "female",
    path: "/relationship-models/female/f051.webp",
    mood: "warm",
    face: "sharp",
    body: "slim",
    style: "romantic",
    energy: "gentle",
  },
  {
    id: "f052",
    gender: "female",
    path: "/relationship-models/female/f052.webp",
    mood: "cold",
    face: "long",
    body: "voluminous",
    style: "sporty",
    energy: "calm",
  },
  {
    id: "f053",
    gender: "female",
    path: "/relationship-models/female/f053.webp",
    mood: "sexy",
    face: "soft",
    body: "athletic",
    style: "luxury",
    energy: "dominant",
  },
  {
    id: "f054",
    gender: "female",
    path: "/relationship-models/female/f054.webp",
    mood: "innocent",
    face: "round",
    body: "balanced",
    style: "minimal",
    energy: "mysterious",
  },
  {
    id: "f055",
    gender: "female",
    path: "/relationship-models/female/f055.webp",
    mood: "confident",
    face: "balanced",
    body: "slim",
    style: "office",
    energy: "active",
  },
  {
    id: "f056",
    gender: "female",
    path: "/relationship-models/female/f056.webp",
    mood: "mature",
    face: "sharp",
    body: "voluminous",
    style: "casual",
    energy: "gentle",
  },
  {
    id: "f057",
    gender: "female",
    path: "/relationship-models/female/f057.webp",
    mood: "clean",
    face: "long",
    body: "athletic",
    style: "romantic",
    energy: "calm",
  },
  {
    id: "f058",
    gender: "female",
    path: "/relationship-models/female/f058.webp",
    mood: "warm",
    face: "soft",
    body: "balanced",
    style: "sporty",
    energy: "dominant",
  },
  {
    id: "f059",
    gender: "female",
    path: "/relationship-models/female/f059.webp",
    mood: "cold",
    face: "round",
    body: "slim",
    style: "luxury",
    energy: "mysterious",
  },
  {
    id: "f060",
    gender: "female",
    path: "/relationship-models/female/f060.webp",
    mood: "sexy",
    face: "balanced",
    body: "voluminous",
    style: "minimal",
    energy: "active",
  },
  {
    id: "f061",
    gender: "female",
    path: "/relationship-models/female/f061.webp",
    mood: "innocent",
    face: "sharp",
    body: "athletic",
    style: "office",
    energy: "gentle",
  },
  {
    id: "f062",
    gender: "female",
    path: "/relationship-models/female/f062.webp",
    mood: "confident",
    face: "long",
    body: "balanced",
    style: "casual",
    energy: "calm",
  },
  {
    id: "f063",
    gender: "female",
    path: "/relationship-models/female/f063.webp",
    mood: "mature",
    face: "soft",
    body: "slim",
    style: "romantic",
    energy: "dominant",
  },
  {
    id: "f064",
    gender: "female",
    path: "/relationship-models/female/f064.webp",
    mood: "clean",
    face: "round",
    body: "voluminous",
    style: "sporty",
    energy: "mysterious",
  },
  {
    id: "f065",
    gender: "female",
    path: "/relationship-models/female/f065.webp",
    mood: "warm",
    face: "balanced",
    body: "athletic",
    style: "luxury",
    energy: "active",
  },
  {
    id: "f066",
    gender: "female",
    path: "/relationship-models/female/f066.webp",
    mood: "cold",
    face: "sharp",
    body: "balanced",
    style: "minimal",
    energy: "gentle",
  },
  {
    id: "f067",
    gender: "female",
    path: "/relationship-models/female/f067.webp",
    mood: "sexy",
    face: "long",
    body: "slim",
    style: "office",
    energy: "calm",
  },
  {
    id: "f068",
    gender: "female",
    path: "/relationship-models/female/f068.webp",
    mood: "innocent",
    face: "soft",
    body: "voluminous",
    style: "casual",
    energy: "dominant",
  },
  {
    id: "f069",
    gender: "female",
    path: "/relationship-models/female/f069.webp",
    mood: "confident",
    face: "round",
    body: "athletic",
    style: "romantic",
    energy: "mysterious",
  },
  {
    id: "f070",
    gender: "female",
    path: "/relationship-models/female/f070.webp",
    mood: "mature",
    face: "balanced",
    body: "balanced",
    style: "sporty",
    energy: "active",
  },
  {
    id: "f071",
    gender: "female",
    path: "/relationship-models/female/f071.webp",
    mood: "clean",
    face: "sharp",
    body: "slim",
    style: "luxury",
    energy: "gentle",
  },
  {
    id: "f072",
    gender: "female",
    path: "/relationship-models/female/f072.webp",
    mood: "warm",
    face: "long",
    body: "voluminous",
    style: "minimal",
    energy: "calm",
  },
  {
    id: "f073",
    gender: "female",
    path: "/relationship-models/female/f073.webp",
    mood: "cold",
    face: "soft",
    body: "athletic",
    style: "office",
    energy: "dominant",
  },
  {
    id: "f074",
    gender: "female",
    path: "/relationship-models/female/f074.webp",
    mood: "sexy",
    face: "round",
    body: "balanced",
    style: "casual",
    energy: "mysterious",
  },
  {
    id: "f075",
    gender: "female",
    path: "/relationship-models/female/f075.webp",
    mood: "innocent",
    face: "balanced",
    body: "slim",
    style: "romantic",
    energy: "active",
  },
  {
    id: "f076",
    gender: "female",
    path: "/relationship-models/female/f076.webp",
    mood: "confident",
    face: "sharp",
    body: "voluminous",
    style: "sporty",
    energy: "gentle",
  },
  {
    id: "f077",
    gender: "female",
    path: "/relationship-models/female/f077.webp",
    mood: "mature",
    face: "long",
    body: "athletic",
    style: "luxury",
    energy: "calm",
  },
  {
    id: "f078",
    gender: "female",
    path: "/relationship-models/female/f078.webp",
    mood: "clean",
    face: "soft",
    body: "balanced",
    style: "minimal",
    energy: "dominant",
  },
  {
    id: "f079",
    gender: "female",
    path: "/relationship-models/female/f079.webp",
    mood: "warm",
    face: "round",
    body: "slim",
    style: "office",
    energy: "mysterious",
  },
  {
    id: "f080",
    gender: "female",
    path: "/relationship-models/female/f080.webp",
    mood: "cold",
    face: "balanced",
    body: "voluminous",
    style: "casual",
    energy: "active",
  },
  {
    id: "f081",
    gender: "female",
    path: "/relationship-models/female/f081.webp",
    mood: "sexy",
    face: "sharp",
    body: "athletic",
    style: "romantic",
    energy: "gentle",
  },
  {
    id: "f082",
    gender: "female",
    path: "/relationship-models/female/f082.webp",
    mood: "innocent",
    face: "long",
    body: "balanced",
    style: "sporty",
    energy: "calm",
  },
  {
    id: "f083",
    gender: "female",
    path: "/relationship-models/female/f083.webp",
    mood: "confident",
    face: "soft",
    body: "slim",
    style: "luxury",
    energy: "dominant",
  },
  {
    id: "f084",
    gender: "female",
    path: "/relationship-models/female/f084.webp",
    mood: "mature",
    face: "round",
    body: "voluminous",
    style: "minimal",
    energy: "mysterious",
  },
  {
    id: "f085",
    gender: "female",
    path: "/relationship-models/female/f085.webp",
    mood: "clean",
    face: "balanced",
    body: "athletic",
    style: "office",
    energy: "active",
  },
  {
    id: "f086",
    gender: "female",
    path: "/relationship-models/female/f086.webp",
    mood: "warm",
    face: "sharp",
    body: "balanced",
    style: "casual",
    energy: "gentle",
  },
  {
    id: "f087",
    gender: "female",
    path: "/relationship-models/female/f087.webp",
    mood: "cold",
    face: "long",
    body: "slim",
    style: "romantic",
    energy: "calm",
  },
  {
    id: "f088",
    gender: "female",
    path: "/relationship-models/female/f088.webp",
    mood: "sexy",
    face: "soft",
    body: "voluminous",
    style: "sporty",
    energy: "dominant",
  },
  {
    id: "f089",
    gender: "female",
    path: "/relationship-models/female/f089.webp",
    mood: "innocent",
    face: "round",
    body: "athletic",
    style: "luxury",
    energy: "mysterious",
  },
  {
    id: "f090",
    gender: "female",
    path: "/relationship-models/female/f090.webp",
    mood: "confident",
    face: "balanced",
    body: "balanced",
    style: "minimal",
    energy: "active",
  },
  {
    id: "f091",
    gender: "female",
    path: "/relationship-models/female/f091.webp",
    mood: "mature",
    face: "sharp",
    body: "slim",
    style: "office",
    energy: "gentle",
  },
  {
    id: "f092",
    gender: "female",
    path: "/relationship-models/female/f092.webp",
    mood: "clean",
    face: "long",
    body: "voluminous",
    style: "casual",
    energy: "calm",
  },
  {
    id: "f093",
    gender: "female",
    path: "/relationship-models/female/f093.webp",
    mood: "warm",
    face: "soft",
    body: "athletic",
    style: "romantic",
    energy: "dominant",
  },
  {
    id: "f094",
    gender: "female",
    path: "/relationship-models/female/f094.webp",
    mood: "cold",
    face: "round",
    body: "balanced",
    style: "sporty",
    energy: "mysterious",
  },
  {
    id: "f095",
    gender: "female",
    path: "/relationship-models/female/f095.webp",
    mood: "sexy",
    face: "balanced",
    body: "slim",
    style: "luxury",
    energy: "active",
  },
  {
    id: "f096",
    gender: "female",
    path: "/relationship-models/female/f096.webp",
    mood: "innocent",
    face: "sharp",
    body: "voluminous",
    style: "minimal",
    energy: "gentle",
  },
  {
    id: "f097",
    gender: "female",
    path: "/relationship-models/female/f097.webp",
    mood: "confident",
    face: "long",
    body: "athletic",
    style: "office",
    energy: "calm",
  },
  {
    id: "f098",
    gender: "female",
    path: "/relationship-models/female/f098.webp",
    mood: "mature",
    face: "soft",
    body: "balanced",
    style: "casual",
    energy: "dominant",
  },
  {
    id: "f099",
    gender: "female",
    path: "/relationship-models/female/f099.webp",
    mood: "clean",
    face: "round",
    body: "slim",
    style: "romantic",
    energy: "mysterious",
  },
  {
    id: "f100",
    gender: "female",
    path: "/relationship-models/female/f100.webp",
    mood: "warm",
    face: "balanced",
    body: "voluminous",
    style: "sporty",
    energy: "active",
  },
  {
    id: "f101",
    gender: "female",
    path: "/relationship-models/female/f101.webp",
    mood: "cold",
    face: "sharp",
    body: "athletic",
    style: "luxury",
    energy: "gentle",
  },
  {
    id: "f102",
    gender: "female",
    path: "/relationship-models/female/f102.webp",
    mood: "sexy",
    face: "long",
    body: "balanced",
    style: "minimal",
    energy: "calm",
  },
  {
    id: "f103",
    gender: "female",
    path: "/relationship-models/female/f103.webp",
    mood: "innocent",
    face: "soft",
    body: "slim",
    style: "office",
    energy: "dominant",
  },
  {
    id: "f104",
    gender: "female",
    path: "/relationship-models/female/f104.webp",
    mood: "confident",
    face: "round",
    body: "voluminous",
    style: "casual",
    energy: "mysterious",
  },
  {
    id: "f105",
    gender: "female",
    path: "/relationship-models/female/f105.webp",
    mood: "mature",
    face: "balanced",
    body: "athletic",
    style: "romantic",
    energy: "active",
  },
  {
    id: "f106",
    gender: "female",
    path: "/relationship-models/female/f106.webp",
    mood: "clean",
    face: "sharp",
    body: "balanced",
    style: "sporty",
    energy: "gentle",
  },
  {
    id: "f107",
    gender: "female",
    path: "/relationship-models/female/f107.webp",
    mood: "warm",
    face: "long",
    body: "slim",
    style: "luxury",
    energy: "calm",
  },
  {
    id: "f108",
    gender: "female",
    path: "/relationship-models/female/f108.webp",
    mood: "cold",
    face: "soft",
    body: "voluminous",
    style: "minimal",
    energy: "dominant",
  },
  {
    id: "f109",
    gender: "female",
    path: "/relationship-models/female/f109.webp",
    mood: "sexy",
    face: "round",
    body: "athletic",
    style: "office",
    energy: "mysterious",
  },
  {
    id: "f110",
    gender: "female",
    path: "/relationship-models/female/f110.webp",
    mood: "innocent",
    face: "balanced",
    body: "balanced",
    style: "casual",
    energy: "active",
  },
  {
    id: "f111",
    gender: "female",
    path: "/relationship-models/female/f111.webp",
    mood: "confident",
    face: "sharp",
    body: "slim",
    style: "romantic",
    energy: "gentle",
  },
  {
    id: "f112",
    gender: "female",
    path: "/relationship-models/female/f112.webp",
    mood: "mature",
    face: "long",
    body: "voluminous",
    style: "sporty",
    energy: "calm",
  },
  {
    id: "f113",
    gender: "female",
    path: "/relationship-models/female/f113.webp",
    mood: "clean",
    face: "soft",
    body: "athletic",
    style: "luxury",
    energy: "dominant",
  },
  {
    id: "f114",
    gender: "female",
    path: "/relationship-models/female/f114.webp",
    mood: "warm",
    face: "round",
    body: "balanced",
    style: "minimal",
    energy: "mysterious",
  },
  {
    id: "f115",
    gender: "female",
    path: "/relationship-models/female/f115.webp",
    mood: "cold",
    face: "balanced",
    body: "slim",
    style: "office",
    energy: "active",
  },
  {
    id: "f116",
    gender: "female",
    path: "/relationship-models/female/f116.webp",
    mood: "sexy",
    face: "sharp",
    body: "voluminous",
    style: "casual",
    energy: "gentle",
  },
  {
    id: "f117",
    gender: "female",
    path: "/relationship-models/female/f117.webp",
    mood: "innocent",
    face: "long",
    body: "athletic",
    style: "romantic",
    energy: "calm",
  },
  {
    id: "f118",
    gender: "female",
    path: "/relationship-models/female/f118.webp",
    mood: "confident",
    face: "soft",
    body: "balanced",
    style: "sporty",
    energy: "dominant",
  },
  {
    id: "f119",
    gender: "female",
    path: "/relationship-models/female/f119.webp",
    mood: "mature",
    face: "round",
    body: "slim",
    style: "luxury",
    energy: "mysterious",
  },
  {
    id: "f120",
    gender: "female",
    path: "/relationship-models/female/f120.webp",
    mood: "clean",
    face: "balanced",
    body: "voluminous",
    style: "minimal",
    energy: "active",
  },
  {
    id: "f121",
    gender: "female",
    path: "/relationship-models/female/f121.webp",
    mood: "warm",
    face: "sharp",
    body: "athletic",
    style: "office",
    energy: "gentle",
  },
  {
    id: "f122",
    gender: "female",
    path: "/relationship-models/female/f122.webp",
    mood: "cold",
    face: "long",
    body: "balanced",
    style: "casual",
    energy: "calm",
  },
  {
    id: "f123",
    gender: "female",
    path: "/relationship-models/female/f123.webp",
    mood: "sexy",
    face: "soft",
    body: "slim",
    style: "romantic",
    energy: "dominant",
  },
  {
    id: "f124",
    gender: "female",
    path: "/relationship-models/female/f124.webp",
    mood: "innocent",
    face: "round",
    body: "voluminous",
    style: "sporty",
    energy: "mysterious",
  },
  {
    id: "f125",
    gender: "female",
    path: "/relationship-models/female/f125.webp",
    mood: "confident",
    face: "balanced",
    body: "athletic",
    style: "luxury",
    energy: "active",
  },
  {
    id: "f126",
    gender: "female",
    path: "/relationship-models/female/f126.webp",
    mood: "mature",
    face: "sharp",
    body: "balanced",
    style: "minimal",
    energy: "gentle",
  },
  {
    id: "f127",
    gender: "female",
    path: "/relationship-models/female/f127.webp",
    mood: "clean",
    face: "long",
    body: "slim",
    style: "office",
    energy: "calm",
  },
  {
    id: "f128",
    gender: "female",
    path: "/relationship-models/female/f128.webp",
    mood: "warm",
    face: "soft",
    body: "voluminous",
    style: "casual",
    energy: "dominant",
  },
  {
    id: "f129",
    gender: "female",
    path: "/relationship-models/female/f129.webp",
    mood: "cold",
    face: "round",
    body: "athletic",
    style: "romantic",
    energy: "mysterious",
  },
  {
    id: "f130",
    gender: "female",
    path: "/relationship-models/female/f130.webp",
    mood: "sexy",
    face: "balanced",
    body: "balanced",
    style: "sporty",
    energy: "active",
  },
  {
    id: "f131",
    gender: "female",
    path: "/relationship-models/female/f131.webp",
    mood: "innocent",
    face: "sharp",
    body: "slim",
    style: "luxury",
    energy: "gentle",
  },
  {
    id: "f132",
    gender: "female",
    path: "/relationship-models/female/f132.webp",
    mood: "confident",
    face: "long",
    body: "voluminous",
    style: "minimal",
    energy: "calm",
  },
  {
    id: "f133",
    gender: "female",
    path: "/relationship-models/female/f133.webp",
    mood: "mature",
    face: "soft",
    body: "athletic",
    style: "office",
    energy: "dominant",
  },
  {
    id: "f134",
    gender: "female",
    path: "/relationship-models/female/f134.webp",
    mood: "clean",
    face: "round",
    body: "balanced",
    style: "casual",
    energy: "mysterious",
  },
  {
    id: "f135",
    gender: "female",
    path: "/relationship-models/female/f135.webp",
    mood: "warm",
    face: "balanced",
    body: "slim",
    style: "romantic",
    energy: "active",
  },
  {
    id: "f136",
    gender: "female",
    path: "/relationship-models/female/f136.webp",
    mood: "cold",
    face: "sharp",
    body: "voluminous",
    style: "sporty",
    energy: "gentle",
  },
  {
    id: "f137",
    gender: "female",
    path: "/relationship-models/female/f137.webp",
    mood: "sexy",
    face: "long",
    body: "athletic",
    style: "luxury",
    energy: "calm",
  },
  {
    id: "f138",
    gender: "female",
    path: "/relationship-models/female/f138.webp",
    mood: "innocent",
    face: "soft",
    body: "balanced",
    style: "minimal",
    energy: "dominant",
  },
  {
    id: "f139",
    gender: "female",
    path: "/relationship-models/female/f139.webp",
    mood: "confident",
    face: "round",
    body: "slim",
    style: "office",
    energy: "mysterious",
  },
  {
    id: "f140",
    gender: "female",
    path: "/relationship-models/female/f140.webp",
    mood: "mature",
    face: "balanced",
    body: "voluminous",
    style: "casual",
    energy: "active",
  },
  {
    id: "f141",
    gender: "female",
    path: "/relationship-models/female/f141.webp",
    mood: "clean",
    face: "sharp",
    body: "athletic",
    style: "romantic",
    energy: "gentle",
  },
  {
    id: "f142",
    gender: "female",
    path: "/relationship-models/female/f142.webp",
    mood: "warm",
    face: "long",
    body: "balanced",
    style: "sporty",
    energy: "calm",
  },
  {
    id: "f143",
    gender: "female",
    path: "/relationship-models/female/f143.webp",
    mood: "cold",
    face: "soft",
    body: "slim",
    style: "luxury",
    energy: "dominant",
  },
  {
    id: "f144",
    gender: "female",
    path: "/relationship-models/female/f144.webp",
    mood: "sexy",
    face: "round",
    body: "voluminous",
    style: "minimal",
    energy: "mysterious",
  },
  {
    id: "f145",
    gender: "female",
    path: "/relationship-models/female/f145.webp",
    mood: "innocent",
    face: "balanced",
    body: "athletic",
    style: "office",
    energy: "active",
  },
  {
    id: "f146",
    gender: "female",
    path: "/relationship-models/female/f146.webp",
    mood: "confident",
    face: "sharp",
    body: "balanced",
    style: "casual",
    energy: "gentle",
  },
  {
    id: "f147",
    gender: "female",
    path: "/relationship-models/female/f147.webp",
    mood: "mature",
    face: "long",
    body: "slim",
    style: "romantic",
    energy: "calm",
  },
  {
    id: "f148",
    gender: "female",
    path: "/relationship-models/female/f148.webp",
    mood: "clean",
    face: "soft",
    body: "voluminous",
    style: "sporty",
    energy: "dominant",
  },
  {
    id: "f149",
    gender: "female",
    path: "/relationship-models/female/f149.webp",
    mood: "warm",
    face: "round",
    body: "athletic",
    style: "luxury",
    energy: "mysterious",
  },
  {
    id: "f150",
    gender: "female",
    path: "/relationship-models/female/f150.webp",
    mood: "cold",
    face: "balanced",
    body: "balanced",
    style: "minimal",
    energy: "active",
  },
  {
    id: "f151",
    gender: "female",
    path: "/relationship-models/female/f151.webp",
    mood: "sexy",
    face: "sharp",
    body: "slim",
    style: "office",
    energy: "gentle",
  },
  {
    id: "f152",
    gender: "female",
    path: "/relationship-models/female/f152.webp",
    mood: "innocent",
    face: "long",
    body: "voluminous",
    style: "casual",
    energy: "calm",
  },
  {
    id: "f153",
    gender: "female",
    path: "/relationship-models/female/f153.webp",
    mood: "confident",
    face: "soft",
    body: "athletic",
    style: "romantic",
    energy: "dominant",
  },
  {
    id: "f154",
    gender: "female",
    path: "/relationship-models/female/f154.webp",
    mood: "mature",
    face: "round",
    body: "balanced",
    style: "sporty",
    energy: "mysterious",
  },
  {
    id: "f155",
    gender: "female",
    path: "/relationship-models/female/f155.webp",
    mood: "clean",
    face: "balanced",
    body: "slim",
    style: "luxury",
    energy: "active",
  },
  {
    id: "f156",
    gender: "female",
    path: "/relationship-models/female/f156.webp",
    mood: "warm",
    face: "sharp",
    body: "voluminous",
    style: "minimal",
    energy: "gentle",
  },
  {
    id: "f157",
    gender: "female",
    path: "/relationship-models/female/f157.webp",
    mood: "cold",
    face: "long",
    body: "athletic",
    style: "office",
    energy: "calm",
  },
  {
    id: "f158",
    gender: "female",
    path: "/relationship-models/female/f158.webp",
    mood: "sexy",
    face: "soft",
    body: "balanced",
    style: "casual",
    energy: "dominant",
  },
  {
    id: "f159",
    gender: "female",
    path: "/relationship-models/female/f159.webp",
    mood: "innocent",
    face: "round",
    body: "slim",
    style: "romantic",
    energy: "mysterious",
  },
  {
    id: "f160",
    gender: "female",
    path: "/relationship-models/female/f160.webp",
    mood: "confident",
    face: "balanced",
    body: "voluminous",
    style: "sporty",
    energy: "active",
  },
  {
    id: "f161",
    gender: "female",
    path: "/relationship-models/female/f161.webp",
    mood: "mature",
    face: "sharp",
    body: "athletic",
    style: "luxury",
    energy: "gentle",
  },
  {
    id: "f162",
    gender: "female",
    path: "/relationship-models/female/f162.webp",
    mood: "clean",
    face: "long",
    body: "balanced",
    style: "minimal",
    energy: "calm",
  },
  {
    id: "f163",
    gender: "female",
    path: "/relationship-models/female/f163.webp",
    mood: "warm",
    face: "soft",
    body: "slim",
    style: "office",
    energy: "dominant",
  },
  {
    id: "f164",
    gender: "female",
    path: "/relationship-models/female/f164.webp",
    mood: "cold",
    face: "round",
    body: "voluminous",
    style: "casual",
    energy: "mysterious",
  },
  {
    id: "f165",
    gender: "female",
    path: "/relationship-models/female/f165.webp",
    mood: "sexy",
    face: "balanced",
    body: "athletic",
    style: "romantic",
    energy: "active",
  },
  {
    id: "f166",
    gender: "female",
    path: "/relationship-models/female/f166.webp",
    mood: "innocent",
    face: "sharp",
    body: "balanced",
    style: "sporty",
    energy: "gentle",
  },
  {
    id: "f167",
    gender: "female",
    path: "/relationship-models/female/f167.webp",
    mood: "confident",
    face: "long",
    body: "slim",
    style: "luxury",
    energy: "calm",
  },
  {
    id: "f168",
    gender: "female",
    path: "/relationship-models/female/f168.webp",
    mood: "mature",
    face: "soft",
    body: "voluminous",
    style: "minimal",
    energy: "dominant",
  },
  {
    id: "f169",
    gender: "female",
    path: "/relationship-models/female/f169.webp",
    mood: "clean",
    face: "round",
    body: "athletic",
    style: "office",
    energy: "mysterious",
  },
  {
    id: "f170",
    gender: "female",
    path: "/relationship-models/female/f170.webp",
    mood: "warm",
    face: "balanced",
    body: "balanced",
    style: "casual",
    energy: "active",
  },
  {
    id: "f171",
    gender: "female",
    path: "/relationship-models/female/f171.webp",
    mood: "cold",
    face: "sharp",
    body: "slim",
    style: "romantic",
    energy: "gentle",
  },
  {
    id: "f172",
    gender: "female",
    path: "/relationship-models/female/f172.webp",
    mood: "sexy",
    face: "long",
    body: "voluminous",
    style: "sporty",
    energy: "calm",
  },
  {
    id: "f173",
    gender: "female",
    path: "/relationship-models/female/f173.webp",
    mood: "innocent",
    face: "soft",
    body: "athletic",
    style: "luxury",
    energy: "dominant",
  },
  {
    id: "f174",
    gender: "female",
    path: "/relationship-models/female/f174.webp",
    mood: "confident",
    face: "round",
    body: "balanced",
    style: "minimal",
    energy: "mysterious",
  },
  {
    id: "f175",
    gender: "female",
    path: "/relationship-models/female/f175.webp",
    mood: "mature",
    face: "balanced",
    body: "slim",
    style: "office",
    energy: "active",
  },
  {
    id: "f176",
    gender: "female",
    path: "/relationship-models/female/f176.webp",
    mood: "clean",
    face: "sharp",
    body: "voluminous",
    style: "casual",
    energy: "gentle",
  },
  {
    id: "f177",
    gender: "female",
    path: "/relationship-models/female/f177.webp",
    mood: "warm",
    face: "long",
    body: "athletic",
    style: "romantic",
    energy: "calm",
  },
  {
    id: "f178",
    gender: "female",
    path: "/relationship-models/female/f178.webp",
    mood: "cold",
    face: "soft",
    body: "balanced",
    style: "sporty",
    energy: "dominant",
  },
  {
    id: "f179",
    gender: "female",
    path: "/relationship-models/female/f179.webp",
    mood: "sexy",
    face: "round",
    body: "slim",
    style: "luxury",
    energy: "mysterious",
  },
  {
    id: "f180",
    gender: "female",
    path: "/relationship-models/female/f180.webp",
    mood: "innocent",
    face: "balanced",
    body: "voluminous",
    style: "minimal",
    energy: "active",
  },
  {
    id: "f181",
    gender: "female",
    path: "/relationship-models/female/f181.webp",
    mood: "confident",
    face: "sharp",
    body: "athletic",
    style: "office",
    energy: "gentle",
  },
  {
    id: "f182",
    gender: "female",
    path: "/relationship-models/female/f182.webp",
    mood: "mature",
    face: "long",
    body: "balanced",
    style: "casual",
    energy: "calm",
  },
  {
    id: "f183",
    gender: "female",
    path: "/relationship-models/female/f183.webp",
    mood: "clean",
    face: "soft",
    body: "slim",
    style: "romantic",
    energy: "dominant",
  },
  {
    id: "f184",
    gender: "female",
    path: "/relationship-models/female/f184.webp",
    mood: "warm",
    face: "round",
    body: "voluminous",
    style: "sporty",
    energy: "mysterious",
  },
  {
    id: "f185",
    gender: "female",
    path: "/relationship-models/female/f185.webp",
    mood: "cold",
    face: "balanced",
    body: "athletic",
    style: "luxury",
    energy: "active",
  },
  {
    id: "f186",
    gender: "female",
    path: "/relationship-models/female/f186.webp",
    mood: "sexy",
    face: "sharp",
    body: "balanced",
    style: "minimal",
    energy: "gentle",
  },
  {
    id: "f187",
    gender: "female",
    path: "/relationship-models/female/f187.webp",
    mood: "innocent",
    face: "long",
    body: "slim",
    style: "office",
    energy: "calm",
  },
  {
    id: "f188",
    gender: "female",
    path: "/relationship-models/female/f188.webp",
    mood: "confident",
    face: "soft",
    body: "voluminous",
    style: "casual",
    energy: "dominant",
  },
  {
    id: "f189",
    gender: "female",
    path: "/relationship-models/female/f189.webp",
    mood: "mature",
    face: "round",
    body: "athletic",
    style: "romantic",
    energy: "mysterious",
  },
  {
    id: "f190",
    gender: "female",
    path: "/relationship-models/female/f190.webp",
    mood: "clean",
    face: "balanced",
    body: "balanced",
    style: "sporty",
    energy: "active",
  },
  {
    id: "f191",
    gender: "female",
    path: "/relationship-models/female/f191.webp",
    mood: "warm",
    face: "sharp",
    body: "slim",
    style: "luxury",
    energy: "gentle",
  },
  {
    id: "f192",
    gender: "female",
    path: "/relationship-models/female/f192.webp",
    mood: "cold",
    face: "long",
    body: "voluminous",
    style: "minimal",
    energy: "calm",
  },
  {
    id: "f193",
    gender: "female",
    path: "/relationship-models/female/f193.webp",
    mood: "sexy",
    face: "soft",
    body: "athletic",
    style: "office",
    energy: "dominant",
  },
  {
    id: "f194",
    gender: "female",
    path: "/relationship-models/female/f194.webp",
    mood: "innocent",
    face: "round",
    body: "balanced",
    style: "casual",
    energy: "mysterious",
  },
  {
    id: "f195",
    gender: "female",
    path: "/relationship-models/female/f195.webp",
    mood: "confident",
    face: "balanced",
    body: "slim",
    style: "romantic",
    energy: "active",
  },
  {
    id: "f196",
    gender: "female",
    path: "/relationship-models/female/f196.webp",
    mood: "mature",
    face: "sharp",
    body: "voluminous",
    style: "sporty",
    energy: "gentle",
  },
  {
    id: "f197",
    gender: "female",
    path: "/relationship-models/female/f197.webp",
    mood: "clean",
    face: "long",
    body: "athletic",
    style: "luxury",
    energy: "calm",
  },
  {
    id: "f198",
    gender: "female",
    path: "/relationship-models/female/f198.webp",
    mood: "warm",
    face: "soft",
    body: "balanced",
    style: "minimal",
    energy: "dominant",
  },
  {
    id: "f199",
    gender: "female",
    path: "/relationship-models/female/f199.webp",
    mood: "cold",
    face: "round",
    body: "slim",
    style: "office",
    energy: "mysterious",
  },
  {
    id: "f200",
    gender: "female",
    path: "/relationship-models/female/f200.webp",
    mood: "sexy",
    face: "balanced",
    body: "voluminous",
    style: "casual",
    energy: "active",
  }
];

export const relationshipModels: RelationshipModel[] = [
  ...maleRelationshipModels,
  ...femaleRelationshipModels,
];

function normalizeSeed(seed: number) {
  if (!Number.isFinite(seed)) return 0;
  return Math.abs(Math.trunc(seed));
}

function matchesProfile(
  model: RelationshipModel,
  profile: RelationshipVisualProfile,
  keys: Array<keyof RelationshipVisualProfile>,
) {
  return keys.every((key) => {
    const expected = profile[key];
    return expected === undefined || model[key] === expected;
  });
}

export function getModelsByGender(gender: RelationshipGender) {
  return gender === "male"
    ? maleRelationshipModels
    : femaleRelationshipModels;
}

export function pickRelationshipModel(
  profile: RelationshipVisualProfile,
  seed: number,
): RelationshipModel {
  const gender: RelationshipGender =
    profile.gender === "male" ? "male" : "female";

  const genderPool = getModelsByGender(gender);

  if (genderPool.length === 0) {
    throw new Error(`관계 인물 이미지가 없습니다: ${gender}`);
  }

  const exactKeys: Array<keyof RelationshipVisualProfile> = [
    "mood",
    "face",
    "body",
    "style",
    "energy",
  ];

  const mediumKeys: Array<keyof RelationshipVisualProfile> = [
    "mood",
    "style",
    "energy",
  ];

  const looseKeys: Array<keyof RelationshipVisualProfile> = [
    "mood",
    "energy",
  ];

  const exact = genderPool.filter((model) =>
    matchesProfile(model, profile, exactKeys),
  );

  const medium = genderPool.filter((model) =>
    matchesProfile(model, profile, mediumKeys),
  );

  const loose = genderPool.filter((model) =>
    matchesProfile(model, profile, looseKeys),
  );

  const pool =
    exact.length > 0
      ? exact
      : medium.length > 0
        ? medium
        : loose.length > 0
          ? loose
          : genderPool;

  return pool[normalizeSeed(seed) % pool.length];
}

export function pickDistinctRelationshipModel(
  profile: RelationshipVisualProfile,
  seed: number,
  excludedIds: string[] = [],
): RelationshipModel {
  const gender: RelationshipGender =
    profile.gender === "male" ? "male" : "female";

  const basePool = getModelsByGender(gender);
  const filteredPool = basePool.filter(
    (model) => !excludedIds.includes(model.id),
  );

  if (filteredPool.length === 0) {
    return pickRelationshipModel(profile, seed);
  }

  const preferred = filteredPool.filter((model) =>
    matchesProfile(model, profile, ["mood", "style", "energy"]),
  );

  const pool = preferred.length > 0 ? preferred : filteredPool;
  return pool[normalizeSeed(seed) % pool.length];
}

export function makeRelationshipSeed(input: string) {
  let hash = 2166136261;

  for (let index = 0; index < input.length; index += 1) {
    hash ^= input.charCodeAt(index);
    hash = Math.imul(hash, 16777619);
  }

  return Math.abs(hash);
}

export function validateRelationshipModels() {
  const ids = new Set<string>();
  const paths = new Set<string>();

  for (const model of relationshipModels) {
    if (ids.has(model.id)) {
      throw new Error(`중복 관계 인물 ID: ${model.id}`);
    }

    if (paths.has(model.path)) {
      throw new Error(`중복 관계 인물 경로: ${model.path}`);
    }

    ids.add(model.id);
    paths.add(model.path);
  }

  return {
    total: relationshipModels.length,
    male: maleRelationshipModels.length,
    female: femaleRelationshipModels.length,
  };
}
